/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as YearsRouteImport } from "./routes/years"
import { Route as JournalsRouteImport } from "./routes/journals"
import { Route as DashboardRouteImport } from "./routes/dashboard"
import { Route as ConferencesRouteImport } from "./routes/conferences"
import { Route as ChartsRouteImport } from "./routes/charts"
import { Route as AuthorsRouteImport } from "./routes/authors"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as YearsIndexRouteImport } from "./routes/years.index"
import { Route as JournalsIndexRouteImport } from "./routes/journals.index"
import { Route as ConferencesIndexRouteImport } from "./routes/conferences.index"
import { Route as AuthorsIndexRouteImport } from "./routes/authors.index"
import { Route as YearsYearRouteImport } from "./routes/years.$year"
import { Route as JournalsJournalIdRouteImport } from "./routes/journals.$journalId"
import { Route as ConferencesConferenceIdRouteImport } from "./routes/conferences.$conferenceId"
import { Route as AuthorsAuthorIdRouteImport } from "./routes/authors.$authorId"
import { Route as JournalsJournalIdIndexRouteImport } from "./routes/journals.$journalId.index"
import { Route as ConferencesConferenceIdIndexRouteImport } from "./routes/conferences.$conferenceId.index"
import { Route as JournalsJournalIdArticlesArticleIdRouteImport } from "./routes/journals.$journalId.articles.$articleId"
import { Route as ConferencesConferenceIdArticlesArticleIdRouteImport } from "./routes/conferences.$conferenceId.articles.$articleId"

const YearsRoute = YearsRouteImport.update({
  id: "/years",
  path: "/years",
  getParentRoute: () => rootRouteImport,
} as any)
const JournalsRoute = JournalsRouteImport.update({
  id: "/journals",
  path: "/journals",
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any)
const ConferencesRoute = ConferencesRouteImport.update({
  id: "/conferences",
  path: "/conferences",
  getParentRoute: () => rootRouteImport,
} as any)
const ChartsRoute = ChartsRouteImport.update({
  id: "/charts",
  path: "/charts",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsRoute = AuthorsRouteImport.update({
  id: "/authors",
  path: "/authors",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const YearsIndexRoute = YearsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => YearsRoute,
} as any)
const JournalsIndexRoute = JournalsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => JournalsRoute,
} as any)
const ConferencesIndexRoute = ConferencesIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => ConferencesRoute,
} as any)
const AuthorsIndexRoute = AuthorsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthorsRoute,
} as any)
const YearsYearRoute = YearsYearRouteImport.update({
  id: "/$year",
  path: "/$year",
  getParentRoute: () => YearsRoute,
} as any)
const JournalsJournalIdRoute = JournalsJournalIdRouteImport.update({
  id: "/$journalId",
  path: "/$journalId",
  getParentRoute: () => JournalsRoute,
} as any)
const ConferencesConferenceIdRoute = ConferencesConferenceIdRouteImport.update({
  id: "/$conferenceId",
  path: "/$conferenceId",
  getParentRoute: () => ConferencesRoute,
} as any)
const AuthorsAuthorIdRoute = AuthorsAuthorIdRouteImport.update({
  id: "/$authorId",
  path: "/$authorId",
  getParentRoute: () => AuthorsRoute,
} as any)
const JournalsJournalIdIndexRoute = JournalsJournalIdIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => JournalsJournalIdRoute,
} as any)
const ConferencesConferenceIdIndexRoute =
  ConferencesConferenceIdIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => ConferencesConferenceIdRoute,
  } as any)
const JournalsJournalIdArticlesArticleIdRoute =
  JournalsJournalIdArticlesArticleIdRouteImport.update({
    id: "/articles/$articleId",
    path: "/articles/$articleId",
    getParentRoute: () => JournalsJournalIdRoute,
  } as any)
const ConferencesConferenceIdArticlesArticleIdRoute =
  ConferencesConferenceIdArticlesArticleIdRouteImport.update({
    id: "/articles/$articleId",
    path: "/articles/$articleId",
    getParentRoute: () => ConferencesConferenceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/authors": typeof AuthorsRouteWithChildren
  "/charts": typeof ChartsRoute
  "/conferences": typeof ConferencesRouteWithChildren
  "/dashboard": typeof DashboardRoute
  "/journals": typeof JournalsRouteWithChildren
  "/years": typeof YearsRouteWithChildren
  "/authors/$authorId": typeof AuthorsAuthorIdRoute
  "/conferences/$conferenceId": typeof ConferencesConferenceIdRouteWithChildren
  "/journals/$journalId": typeof JournalsJournalIdRouteWithChildren
  "/years/$year": typeof YearsYearRoute
  "/authors/": typeof AuthorsIndexRoute
  "/conferences/": typeof ConferencesIndexRoute
  "/journals/": typeof JournalsIndexRoute
  "/years/": typeof YearsIndexRoute
  "/conferences/$conferenceId/": typeof ConferencesConferenceIdIndexRoute
  "/journals/$journalId/": typeof JournalsJournalIdIndexRoute
  "/conferences/$conferenceId/articles/$articleId": typeof ConferencesConferenceIdArticlesArticleIdRoute
  "/journals/$journalId/articles/$articleId": typeof JournalsJournalIdArticlesArticleIdRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/charts": typeof ChartsRoute
  "/dashboard": typeof DashboardRoute
  "/authors/$authorId": typeof AuthorsAuthorIdRoute
  "/years/$year": typeof YearsYearRoute
  "/authors": typeof AuthorsIndexRoute
  "/conferences": typeof ConferencesIndexRoute
  "/journals": typeof JournalsIndexRoute
  "/years": typeof YearsIndexRoute
  "/conferences/$conferenceId": typeof ConferencesConferenceIdIndexRoute
  "/journals/$journalId": typeof JournalsJournalIdIndexRoute
  "/conferences/$conferenceId/articles/$articleId": typeof ConferencesConferenceIdArticlesArticleIdRoute
  "/journals/$journalId/articles/$articleId": typeof JournalsJournalIdArticlesArticleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/authors": typeof AuthorsRouteWithChildren
  "/charts": typeof ChartsRoute
  "/conferences": typeof ConferencesRouteWithChildren
  "/dashboard": typeof DashboardRoute
  "/journals": typeof JournalsRouteWithChildren
  "/years": typeof YearsRouteWithChildren
  "/authors/$authorId": typeof AuthorsAuthorIdRoute
  "/conferences/$conferenceId": typeof ConferencesConferenceIdRouteWithChildren
  "/journals/$journalId": typeof JournalsJournalIdRouteWithChildren
  "/years/$year": typeof YearsYearRoute
  "/authors/": typeof AuthorsIndexRoute
  "/conferences/": typeof ConferencesIndexRoute
  "/journals/": typeof JournalsIndexRoute
  "/years/": typeof YearsIndexRoute
  "/conferences/$conferenceId/": typeof ConferencesConferenceIdIndexRoute
  "/journals/$journalId/": typeof JournalsJournalIdIndexRoute
  "/conferences/$conferenceId/articles/$articleId": typeof ConferencesConferenceIdArticlesArticleIdRoute
  "/journals/$journalId/articles/$articleId": typeof JournalsJournalIdArticlesArticleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/authors"
    | "/charts"
    | "/conferences"
    | "/dashboard"
    | "/journals"
    | "/years"
    | "/authors/$authorId"
    | "/conferences/$conferenceId"
    | "/journals/$journalId"
    | "/years/$year"
    | "/authors/"
    | "/conferences/"
    | "/journals/"
    | "/years/"
    | "/conferences/$conferenceId/"
    | "/journals/$journalId/"
    | "/conferences/$conferenceId/articles/$articleId"
    | "/journals/$journalId/articles/$articleId"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/charts"
    | "/dashboard"
    | "/authors/$authorId"
    | "/years/$year"
    | "/authors"
    | "/conferences"
    | "/journals"
    | "/years"
    | "/conferences/$conferenceId"
    | "/journals/$journalId"
    | "/conferences/$conferenceId/articles/$articleId"
    | "/journals/$journalId/articles/$articleId"
  id:
    | "__root__"
    | "/"
    | "/authors"
    | "/charts"
    | "/conferences"
    | "/dashboard"
    | "/journals"
    | "/years"
    | "/authors/$authorId"
    | "/conferences/$conferenceId"
    | "/journals/$journalId"
    | "/years/$year"
    | "/authors/"
    | "/conferences/"
    | "/journals/"
    | "/years/"
    | "/conferences/$conferenceId/"
    | "/journals/$journalId/"
    | "/conferences/$conferenceId/articles/$articleId"
    | "/journals/$journalId/articles/$articleId"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthorsRoute: typeof AuthorsRouteWithChildren
  ChartsRoute: typeof ChartsRoute
  ConferencesRoute: typeof ConferencesRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  JournalsRoute: typeof JournalsRouteWithChildren
  YearsRoute: typeof YearsRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/years": {
      id: "/years"
      path: "/years"
      fullPath: "/years"
      preLoaderRoute: typeof YearsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/journals": {
      id: "/journals"
      path: "/journals"
      fullPath: "/journals"
      preLoaderRoute: typeof JournalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/dashboard": {
      id: "/dashboard"
      path: "/dashboard"
      fullPath: "/dashboard"
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/conferences": {
      id: "/conferences"
      path: "/conferences"
      fullPath: "/conferences"
      preLoaderRoute: typeof ConferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/charts": {
      id: "/charts"
      path: "/charts"
      fullPath: "/charts"
      preLoaderRoute: typeof ChartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/authors": {
      id: "/authors"
      path: "/authors"
      fullPath: "/authors"
      preLoaderRoute: typeof AuthorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/years/": {
      id: "/years/"
      path: "/"
      fullPath: "/years/"
      preLoaderRoute: typeof YearsIndexRouteImport
      parentRoute: typeof YearsRoute
    }
    "/journals/": {
      id: "/journals/"
      path: "/"
      fullPath: "/journals/"
      preLoaderRoute: typeof JournalsIndexRouteImport
      parentRoute: typeof JournalsRoute
    }
    "/conferences/": {
      id: "/conferences/"
      path: "/"
      fullPath: "/conferences/"
      preLoaderRoute: typeof ConferencesIndexRouteImport
      parentRoute: typeof ConferencesRoute
    }
    "/authors/": {
      id: "/authors/"
      path: "/"
      fullPath: "/authors/"
      preLoaderRoute: typeof AuthorsIndexRouteImport
      parentRoute: typeof AuthorsRoute
    }
    "/years/$year": {
      id: "/years/$year"
      path: "/$year"
      fullPath: "/years/$year"
      preLoaderRoute: typeof YearsYearRouteImport
      parentRoute: typeof YearsRoute
    }
    "/journals/$journalId": {
      id: "/journals/$journalId"
      path: "/$journalId"
      fullPath: "/journals/$journalId"
      preLoaderRoute: typeof JournalsJournalIdRouteImport
      parentRoute: typeof JournalsRoute
    }
    "/conferences/$conferenceId": {
      id: "/conferences/$conferenceId"
      path: "/$conferenceId"
      fullPath: "/conferences/$conferenceId"
      preLoaderRoute: typeof ConferencesConferenceIdRouteImport
      parentRoute: typeof ConferencesRoute
    }
    "/authors/$authorId": {
      id: "/authors/$authorId"
      path: "/$authorId"
      fullPath: "/authors/$authorId"
      preLoaderRoute: typeof AuthorsAuthorIdRouteImport
      parentRoute: typeof AuthorsRoute
    }
    "/journals/$journalId/": {
      id: "/journals/$journalId/"
      path: "/"
      fullPath: "/journals/$journalId/"
      preLoaderRoute: typeof JournalsJournalIdIndexRouteImport
      parentRoute: typeof JournalsJournalIdRoute
    }
    "/conferences/$conferenceId/": {
      id: "/conferences/$conferenceId/"
      path: "/"
      fullPath: "/conferences/$conferenceId/"
      preLoaderRoute: typeof ConferencesConferenceIdIndexRouteImport
      parentRoute: typeof ConferencesConferenceIdRoute
    }
    "/journals/$journalId/articles/$articleId": {
      id: "/journals/$journalId/articles/$articleId"
      path: "/articles/$articleId"
      fullPath: "/journals/$journalId/articles/$articleId"
      preLoaderRoute: typeof JournalsJournalIdArticlesArticleIdRouteImport
      parentRoute: typeof JournalsJournalIdRoute
    }
    "/conferences/$conferenceId/articles/$articleId": {
      id: "/conferences/$conferenceId/articles/$articleId"
      path: "/articles/$articleId"
      fullPath: "/conferences/$conferenceId/articles/$articleId"
      preLoaderRoute: typeof ConferencesConferenceIdArticlesArticleIdRouteImport
      parentRoute: typeof ConferencesConferenceIdRoute
    }
  }
}

interface AuthorsRouteChildren {
  AuthorsAuthorIdRoute: typeof AuthorsAuthorIdRoute
  AuthorsIndexRoute: typeof AuthorsIndexRoute
}

const AuthorsRouteChildren: AuthorsRouteChildren = {
  AuthorsAuthorIdRoute: AuthorsAuthorIdRoute,
  AuthorsIndexRoute: AuthorsIndexRoute,
}

const AuthorsRouteWithChildren =
  AuthorsRoute._addFileChildren(AuthorsRouteChildren)

interface ConferencesConferenceIdRouteChildren {
  ConferencesConferenceIdIndexRoute: typeof ConferencesConferenceIdIndexRoute
  ConferencesConferenceIdArticlesArticleIdRoute: typeof ConferencesConferenceIdArticlesArticleIdRoute
}

const ConferencesConferenceIdRouteChildren: ConferencesConferenceIdRouteChildren =
  {
    ConferencesConferenceIdIndexRoute: ConferencesConferenceIdIndexRoute,
    ConferencesConferenceIdArticlesArticleIdRoute:
      ConferencesConferenceIdArticlesArticleIdRoute,
  }

const ConferencesConferenceIdRouteWithChildren =
  ConferencesConferenceIdRoute._addFileChildren(
    ConferencesConferenceIdRouteChildren,
  )

interface ConferencesRouteChildren {
  ConferencesConferenceIdRoute: typeof ConferencesConferenceIdRouteWithChildren
  ConferencesIndexRoute: typeof ConferencesIndexRoute
}

const ConferencesRouteChildren: ConferencesRouteChildren = {
  ConferencesConferenceIdRoute: ConferencesConferenceIdRouteWithChildren,
  ConferencesIndexRoute: ConferencesIndexRoute,
}

const ConferencesRouteWithChildren = ConferencesRoute._addFileChildren(
  ConferencesRouteChildren,
)

interface JournalsJournalIdRouteChildren {
  JournalsJournalIdIndexRoute: typeof JournalsJournalIdIndexRoute
  JournalsJournalIdArticlesArticleIdRoute: typeof JournalsJournalIdArticlesArticleIdRoute
}

const JournalsJournalIdRouteChildren: JournalsJournalIdRouteChildren = {
  JournalsJournalIdIndexRoute: JournalsJournalIdIndexRoute,
  JournalsJournalIdArticlesArticleIdRoute:
    JournalsJournalIdArticlesArticleIdRoute,
}

const JournalsJournalIdRouteWithChildren =
  JournalsJournalIdRoute._addFileChildren(JournalsJournalIdRouteChildren)

interface JournalsRouteChildren {
  JournalsJournalIdRoute: typeof JournalsJournalIdRouteWithChildren
  JournalsIndexRoute: typeof JournalsIndexRoute
}

const JournalsRouteChildren: JournalsRouteChildren = {
  JournalsJournalIdRoute: JournalsJournalIdRouteWithChildren,
  JournalsIndexRoute: JournalsIndexRoute,
}

const JournalsRouteWithChildren = JournalsRoute._addFileChildren(
  JournalsRouteChildren,
)

interface YearsRouteChildren {
  YearsYearRoute: typeof YearsYearRoute
  YearsIndexRoute: typeof YearsIndexRoute
}

const YearsRouteChildren: YearsRouteChildren = {
  YearsYearRoute: YearsYearRoute,
  YearsIndexRoute: YearsIndexRoute,
}

const YearsRouteWithChildren = YearsRoute._addFileChildren(YearsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthorsRoute: AuthorsRouteWithChildren,
  ChartsRoute: ChartsRoute,
  ConferencesRoute: ConferencesRouteWithChildren,
  DashboardRoute: DashboardRoute,
  JournalsRoute: JournalsRouteWithChildren,
  YearsRoute: YearsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
